fix accessibility issues
HanaSabih/Portfolio pull request #7
Opened 2022-12-13 13:40 UTC by HanaSabih

Performed following accessibility checks on portfolio project

1. Page title -meaningful title  already exists
2. Image text alternatives - all images in the project have text alternatives.
3. Text headings - All sections in the project have titles
4. Color contrast - Color Contrast was determined by the Figma design
5. Resize - All text contents in the project are zoomable and have no distortions
6. Interaction - Input form elements are labeled and hidden in the mobile version and displayed in desktop versions per the FIGMA design template.
7. Moving content - the webpage has no moving 
8. Multimedia - the web page has no multimedia(audio/video)
9. Basic structure of the page and the navigation menu links are meaningful and self-explanatory

2022-12-13 16:57 UTC, iambenkis requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @HanaSabih 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project, but you are almost there!

## To Highlight 🎉
:heavy_check_mark: Following Linters 
:heavy_check_mark: Following GitHub Flow
:heavy_check_mark: Basic Structure is good
:heavy_check_mark: Can be maximized upto 200%

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️

- [ ] Good job integrating the accessibility in your website, however make sure you have the ` alternativea`  here, it will make your website more accessible since your portfolio will be viewed by different people.
![Screenshot from 2022-12-13 18-37-08](https://user-images.githubusercontent.com/80458199/207393513-fa5f9a69-109c-49fe-81fc-2d97251408e7.png)

- [ ] Kindly remove this `h5` inside the `a` tag , it will make your website respect the heading
![Screenshot from 2022-12-13 18-50-38](https://user-images.githubusercontent.com/80458199/207394699-8b2cc865-e52b-44e2-8291-f64831c524cb.png)

- [ ] Make sure you have here an `h2` tag because you already have an `h1` before it :+1: 
![Screenshot from 2022-12-13 18-53-04](https://user-images.githubusercontent.com/80458199/207395218-0dd4d4eb-cd34-42e0-93ec-f92bb6061261.png)


_Check the button under the review_

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me `@iambenkis` in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-13 16:57 UTC, iambenkis commented on index.html
>          </h1>
- [ ] Good job with this `h1` tag here :+1: , Keep doing the good work :+1:

2022-12-13 16:57 UTC, iambenkis commented on index.html
>          <input
- [ ] Good job with this `input`  labelled here :+1: , keep doing the good work :+1:

2022-12-14 08:44 UTC, emmiiorji approved these changes
Hi @HanaSabih and team,

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congrats](https://user-images.githubusercontent.com/20554583/207525547-7de7920a-360e-47f2-b4e7-69e3afa2af50.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Adhered to GitHub flow
- Requested change has been implemented

### Note:
- This is a pair programming project as stated by the [submission mode](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md#work-and-submission-mode), however, only one of the team members seems to have made commits. Kindly ensure that in subsequent pair programming activities, all the members of the team contribute to the project evidenced by their commits. I have waved this requirement because the previous reviewer seemed to have missed that out.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 08:50 UTC, merged